### ISSUE TITLE
Wiki Feedback

### ISSUE THREAD

**Issue by edherm** [Run5/GoodTrails#13]
Hello! 

I am reviewing all group wikis today and wanted to drop this here for y’all to take a look at.

## MVP Feature List
- [x] Will users be able to edit or delete collections and reviews?

## User Stories
- [x] If users are able to remove trails from their collections, please add a user story for that.

## API Routes
- [x] What functionality will your API routes have? For instance, will you be preventing a full-page reload when a user logs in or registers?

Once these are taken care of, please drop your responses/updates here as a response to this issue.

Thanks, y'all!!
Ed

**Comment by Machaelmus** [comment]
Q #1: Will users be able to edit or delete collections and reviews? 
A: Yes. 

If users are able to remove trails from their collections, please add a user story for that.
Just added! :) 

API routes have also been updated! :D
